name: Terraform
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  check-format:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff

  validate:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    strategy:
      matrix: {
        dir: ['examples/test']
      }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: ${{ matrix.dir }}
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.dir }}

  mock-plan:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    strategy:
      matrix: {
        dir: ['examples/test']
      }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: ${{ matrix.dir }}
      - name: Terraform Plan (Mock)
        run: terraform plan
        working-directory: ${{ matrix.dir }}